# Generated by Django 3.1.5 on 2021-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
